---
- name: Add Nodesource repositories for Node.js.
  yum:
    name: "https://rpm.nodesource.com/pub_0.12/el/{{ ansible_distribution_major_version }}/{{ ansible_architecture }}/nodejs-0.12.7-1nodesource.el6.x86_64.rpm"
    state: present

- name: Ensure Node.js and npm are installed.
  yum: "name=nodejs state=present enablerepo='epel,nodesource'"